asset_issuers:
  XLM:    "Stellar Foundation"
  # XAGTOK: "GAA2LE33JQENL3AJ2JG4QIRMQNC3WL26LDSHSMET5JW42H24CE4ZLANW"
  # PI:     "GB2EP6MYXXUVVE2DJEN5OUNUO75M2YR4HBFIQKWGAUETATRW2LXCD6HG"
  USDC:   "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN"
  # Add other assets and their issuers as needed
