stellar_api_key: "GAOHRNEIAIWX42ONJ5R25X3C4R45GGPWPSHODW4ZWNMUJYFXVATF7PWL"
trading_pair: "XLM/USD"
initial_balance: 1000

asset_issuers:
  USD: "GCYQVVHCPRJEN7HUGAZHBNFD6OZJTZLRDR5KZB7TY7YEO4PH5AWI2EF4"
  BTC: "GBSTRUSD4RJ6XY57NYCUHY3SDDA5MYCYPOUBEKLYMT3MHY7VCOFRHCU7"  # Replace with actual issuer
  # Add other assets and their issuers as needed
